[package]
name = "pw"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.12.1"
anyhow = "1.0.104"
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
clap = { version = "4.6.6", features = ["derive"] }
directories = "6.0.0"
rand = "0.8.8"
rpassword = "7.5.4"

[dev-dependencies]
tempfile = "3.27.0"
